server:
  port: 8081

spring:
  application:
  name:
    employee-service
  datasource:
      url: jdbc:mysql://localhost:3306/employee_service
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


#     database-platform: org.hibernate.dialect.MySQL8Dialect