server:
  port: 8091

spring:
  application:
    name: leave-service
  datasource:
    url: jdbc:mysql://localhost:3306/task_portal
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        hbm2ddl:
          auto: update
